theme: jekyll-theme-minimal
title: [Scott Dallman]
description: [Economist, U.S. Census Bureau]
logo: ["https://github.com/scottdallman/scottdallman.github.io/blob/4f44ac94bc2b5caf1e98fde01cc838428e40ac77/images/IMG-3356.JPG"]

