theme: minima
minima:
  skin: dark
  social_links:
    twitter: scott_dallman 
    github: scottdallman
    linkedin: Scott Dallman
  
    
title: Scott Dallman
description: Economist \newline
             Center for Enterprise Dissemination (CED) \newline
             U.S. Census Bureau \newline
             [scott.j.dallman@census.gov](scott.j.dallman@census.gov)

header_pages: 
    - index.md
    - research.md
    - cv.md
    
google_analytics: UA-NNNNNNNN-N
