remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
    
title: Scott Dallman
description: scott.j.dallman@census.gov
logo: https://media-exp1.licdn.com/dms/image/C5603AQFZTtTMKtNqzA/profile-displayphoto-shrink_800_800/0/1571363370391?e=1635379200&v=beta&t=OJg1G7cGSJSy6LVnShgI75ATxBkx62VBDi91ds18VQo
header_pages: 
- index.md
    
