theme: minima
minima:
  skin: dark
  social_links:
    twitter: scott_dallman 
    github: scottdallman
    linkedin: Scott Dallman
  
    
title: Scott Dallman
description: scott.j.dallman@census.gov

header_pages: 
    - index.md
    
google_analytics: UA-NNNNNNNN-N
