theme: minima
skin: dark
social_links:
    twitter: jekyllrb
    github: jekyll
    linkedin: jekyll
    
title: Scott Dallman
description: Economist 
             Center for Enterprise Dissemination (CED) 
             U.S. Census Bureau 
             [scott.j.dallman@census.gov](scott.j.dallman@census.gov)


